sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - export CXX="g++-4.8" CC="gcc-4.8"

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - make test

